### ISSUE TITLE
How to slow down?

### ISSUE THREAD

**Issue by yukang2017** [deepmind/pysc2#32] opened 2017-08-14 14:43 UTC
When I run an agent, the frame speed of the game is too fast. Would you please tell us where to modify the parameter of game speed?

**Comment by tylerwhipple** [comment] 2017-08-14 15:03
Hey yukang, I believe it has to do with the fps parameter as well as the step_mul but I cannot figure out either with the Agent. 

in play fps is set as a flag but not in the agent (and i am not good at python enough to figure out how)

**Comment by yukang2017** [comment] 2017-08-14 15:08
@tylerwhipple  Thank you! 
In bin/play.py there are:
flags.DEFINE_float("fps", 22.4, "Frames per second to run the game.")
flags.DEFINE_integer("step_mul", 1, "Game steps per observation.")
But they cannot be found in bin/agent.py

**Comment by tylerwhipple** [comment] 2017-08-14 15:10
Yes exactly. Any idea of how to implement them within the bin/agent? or do we pray one of the maintainers to help us out? (I have no idea how to do it easily)

**Comment by tewalds** [comment] 2017-08-14 15:55
This is a duplicate of #22. There's currently no easy way to do it as I've been assuming that you'd want your agents to run/train as quickly as possible. You can view the resulting replays at whatever speed you want either in the game or with bin/play.

**Closed by tewalds** 2017-08-14 15:55 UTC
Labels: duplicate
