### ISSUE TITLE
Unit tags are stored in int32, but are larger than int32

### ISSUE THREAD

**Issue by StephAO** [deepmind/pysc2#244] opened 2018-11-06 16:06 UTC
When using setting the use_raw_units flag in AgentInterfaceFormat, part of the observation is supposed to the unit's tag number. In pysc2/lib/features.py, on line 1013, these tags are stored in a numpy array of dtype int32, however the tags are often numbers greater than what an int32 can store, and therefore the tag number gets distorted.

**Comment by tewalds** [comment] 2018-11-09 15:34
This is a duplicate of #240

**Closed by tewalds** 2018-11-09 15:34 UTC
